name: toolbelt test
on:
  workflow_dispatch: # testing only, trigger manually to test it works
  push:
    branches:
      - main
    tags:
      - "v*"
permissions: read-all
jobs:
  toolbelt:
    permissions:
      contents: write # To upload assets to release.
      packages: write # To publish container images to GHCR
      id-token: write # needed for signing the images with GitHub OIDC Token
    uses: ossf/toolbelt/.github/workflows/toolbelt.yaml@toolbelt-workflow
